### ISSUE TITLE
502 bad gateway / 500 internal server error since 1.4.2 and later

### ISSUE THREAD

**Issue by shadowking001** [linuxserver/docker-chevereto#13]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Website should load correctly
## Current Behavior

Got alternatively 502/500 errors.
## Context
I'm using Chevereto for a year actually. It runs behind SWAG with Authelia and fail2ban.
It behaves normally until version 1.4.1. Since 1.4.2 and later (I tried 1.5.1 yesterday), I can't connect anymore.
## Steps to Reproduce

1. Setup Chevereto through docker-compose.
2. Can't access website
3.
4.

## Environment
**OS:** Debian 11
**CPU architecture:** x86_64
**How docker service was installed:** Official repo, docker-compose layer.

## Command used to create docker container (run/create/compose/screenshot)

Docker-compose file :
```
version: '2.1'
services:

   chevereto:
      image: ghcr.io/linuxserver/chevereto
      container_name: chevereto
      networks:
         - net-db
         - net-proxy
      environment:
         - PUID=1001
         - PGID=1001
         - TZ=Europe/Brussels
      volumes:
         - /opt/chevereto/config:/config
         - /opt/chevereto/data:/data
      labels:
         - "com.centurylinklabs.watchtower.enable=true"
      restart: unless-stopped

networks:

   net-proxy:
      external: true

   net-db:
      external: true
```

Chevereto subdomain configuration file :
```
## Version 2021/06/28
# make sure that your dns has a cname set for chevereto and that your chevereto container is not using a base url

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name chevereto.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable GeoIP bloking
    #include /config/nginx/geoip2_frbe.conf;

    # enable for Authelia
    include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app chevereto;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

## Docker logs

Docker logs don't return anything useful, but here is my SWAG's Nginx error log when I try to reach the website :

`[error] 534#534: *403 connect() failed (111: Connection refused) while connecting to upstream, client: 81.241.xxx.xxx, server: chevereto.*, request: "GET /content/images/system/default/favicon.png HTTP/2.0", upstream: "http://[fd00:abcd:ef00:18::8]:80/content/images/system/default/favicon.png", host: "chevereto.xxx.ovh", referrer: "https://chevereto.xxx.ovh/"`
