### ISSUE TITLE
Composer dependencies PHP 7.4.0 (1.4.0 release)

### ISSUE THREAD

**Issue by shadowking001** [linuxserver/docker-chevereto#8]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Chevereto running fine
## Current Behavior

Since 1.4.0, instead of landing on the main page, I got the following page with this message :
`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0".`
## Steps to Reproduce

1. Upgrade Chevereto to 1.4.0
2. Error page
3. Downgrade to 1.3.0
4. Running fine

## Environment
**OS:** Linux 4.19.0-17-cloud-amd64 SMP Debian 4.19.194-2 (2021-06-21)
**CPU architecture:** x86_64 GNU/Linux
**How docker service was installed:** from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)

My docker-compose file :
```
version: '2.1'
services:

   chevereto:
      image: linuxserver/chevereto
      container_name: chevereto
      networks:
         - net-db
         - net-proxy
      environment:
         - PUID=1001
         - PGID=1001
         - TZ=Europe/Brussels
      volumes:
         - /opt/chevereto/config:/config
         - /opt/chevereto/data:/data
      labels:
#         - "diun.enable=true"
         - "com.centurylinklabs.watchtower.enable=true"
      restart: unless-stopped

networks:

   net-proxy:
      external: true

   net-db:
      external: true
```

## Docker logs

Nothing in docker stdout logs, but this in nginx error.log :
`2021/07/19 10:28:26 [error] 364#364: *45 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.29. in /app/chevereto/app/vendor/composer/platform_check.php on line 24" while reading response header from upstream, client: 172.18.0.5, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "chevereto.ndd.tld"`
